### ISSUE TITLE
tabs vs. spaces

### ISSUE THREAD

**Issue by gpunktschmitz** [nicholasdille/professional-powershell#39]
could you explain/add a line to why you state to use (4) spaces instead of tabs? why is this considered professional and not tabs/2 spaces?

**Comment by nicholasdille** [comment]
Tabs are considered bad habit because they can be interpreted differently, i.e. a question of how many spaces to are considered a tab.

Regarding your question about the choice of four spaces, if you choose smaller indentation it becomes harder to discern different levels while more spaces make lines longer than necessary. But this can quickly become a philosophical/religious discussion ;-)

This will be addressed in #31.
